version: '3.7'

services:
  r3-mvp-stack:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        GO_VERSION: "1.21.4"
        NODE_VERSION: "18"
        PNPM_VERSION: "8"
    command: sleep infinity
    user: r3-mvp-stack
    volumes:
      - .:/workspace:cached
